#Numpy functions and command

Function : function is used to work with array, matrices , statics and linear algebra

Installation command : 1.pip install numpy
                       2.conda install numpy (This command only used in anaconda)
                       
Importing command :

1. np.amax : Returns maximum value in array
2. np.amin : Returns minimum value in array
3. np.mean : Returns the average of the array elements
4. np.median : Returns the median of the array elements
5. np.ptp : Range of values (maximum - minimum)
6. np.std : Returns the standard deviation
7. np.var : Returns variance of the array element
8. np.average : Compute the weighted average 
9. np.percentile : Compute the percentile of array element
10. np.corrcoef : Returns correlation coefficients
11. np.sum : Sum of the array elements
12. np.array : Creates an array
13. np.matrix : Returns matrix from array
14. np.transpose : Gives matrix transpose of an array


Sub-Packages : Random



In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Pc\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




Note: you may need to restart the kernel to use updated packages.

conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | 3          |   3% 
conda-4.14.0         | 937 KB    | 5          |   5% 
conda-4.14.0         | 937 KB    | 6          |   7% 
conda-4.14.0         | 937 KB    | 8         

In [3]:
pip list


Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [4]:
pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [5]:
import numpy as np

In [6]:
print(np.__version__)

1.21.5


In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
print(np.amin(arr))

1


In [11]:
print(np.amax(arr))

10


In [12]:
print(np.mean(arr))
print(np.median(arr))
print(np.ptp(arr))
print(np.std(arr))
print(np.var(arr))
print(np.average(arr))
print(np.percentile(arr))

5.5
5.5
9
2.8722813232690143
8.25
5.5


TypeError: _percentile_dispatcher() missing 1 required positional argument: 'q'

In [13]:
print(np.percentile(arr,10))

1.9


In [18]:
arr = np.array([3,2,1])
arr

array([3, 2, 1])

In [19]:
np.sort(arr)

array([1, 2, 3])

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
print(arr.ndim)

2


In [30]:
print(arr.shape)

(3, 4)


In [32]:
print(type(arr))

<class 'numpy.ndarray'>


In [33]:
print(arr.data)

# Random Number Generator Using numpy

In [53]:
#Generate Random Integer

from numpy import random
x = random.randint(100)
print(x)

40


In [45]:
# Generate Random Float
x = random.rand()
print(x)

0.2695653534381297


In [55]:
#Generate random integer with size
from numpy import random
x = random.randint(100,size=(2))
print(x)

[ 2 59]


In [59]:
#Genrate a 2-D array with 3 rows,each row containing 5 random integers
#random.seed function fixes value which will not change
from numpy import random
random.seed(101)
x = random.randint(100,size=(3,5))
print(x)

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


# 2.4 Practical : Creating scalar in Numpy

In [60]:
#Creating 1-D list
list1 = [1,2,3]

#Creating 1-D list Vertical

list2 = [[10],
         [20],
         [30]]
#Create Vector1

vector1= np.array(list1)
vector2= np.array(list2)

print("Horizontal Vector")
print(vector1)

print("--------------")

print("Vertical Vector")
print(vector2)

Horizontal Vector
[1 2 3]
--------------
Vertical Vector
[[10]
 [20]
 [30]]


#  Creating Matrix in Numpy

In [65]:
a = np.matrix('1 2;3 4')
print("via string input : \n",a,"\n\n")

#array-like input

b = np.matrix([[5,6,7],[4,6]])
print("via array-like input : \n",b)

via string input : 
 [[1 2]
 [3 4]] 


via array-like input : 
 [[list([5, 6, 7]) list([4, 6])]]


C:\Users\Pc\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


# Matrix Multiplication in Numpy


In [66]:
A = 5
B = [[6,7],
     [8,9]]

print(np.dot(A,B))


[[30 35]
 [40 45]]


In [67]:
A = [[6,7],
    [8,9]]

B = 3

print(np.dot(A,B))

[[18 21]
 [24 27]]


In [2]:
import numpy as np
A = [[6,7],
    [3,4]]

B = [[1,2],
    [2,3]]

print(np.dot(A,B))

print("--------")

print(np.dot(B,A))

[[20 33]
 [11 18]]
--------
[[12 15]
 [21 26]]


In [3]:
A = ([1,2,3],[4,5,6],[7,8,9])

np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Percentile & interquartile in Numpy


In [5]:
import numpy as np
data = [32,36,46,46,56,69,75,79,79,88,89,91,92,93,96]

#first quartile(Q1)
Q1 = np.median(data[:10])
print(Q1, '\n')

#third quartile
Q3 = np.median(data[10:])
print(Q3, '\n')

#interquartile range

IQR = Q3-Q1

print('IQR = Q3 - Q1',IQR)

62.5 

92.0 

IQR = Q3 - Q1 29.5


# Array Broadcasting in Numpy  

In [6]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])

a*b

array([2., 4., 6.])

In [ ]:
# a = np.array([1.0,2.0,3.0])
b = 2.0

a*b

#  Calculate BMI of cricket players


In [13]:
#Heights of players

hg_in = [61,65,64,69,70,68,64,63,62,66,72]

#covert into numpy array
         
ht_np = np.array(hg_in)
         
#convert height from inch to meter by exposing it to 0.0245
         
ht_np = ht_np * 0.0245         

ht_np

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [12]:
#weight of players in pound 

wt_pd = [100,200,160,180,140,155,165,172,180,200,168]

#convert into numpy array

wt_np = np.array(wt_pd)

#convert weight from pound to kg by exposing it to 0.45

wt_np = wt_np * 0.45

wt_np

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [14]:
#BMI calculation

BMI = wt_np/(ht_np**2)
BMI

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658,
       25.13010006, 30.19981909, 32.48835283, 35.10503991, 34.42091966,
       24.29543246])

In [15]:
BMI[-1]

24.295432458697764

In [16]:
BMI[BMI<21]

array([20.1474773])

In [17]:
BMI[:5]

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658])

In [19]:
players = np.array([wt_np,ht_np])
players

array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.4945,  1.5925,  1.568 ,  1.6905,  1.715 ,  1.666 ,  1.568 ,
         1.5435,  1.519 ,  1.617 ,  1.764 ]])

In [22]:
players[0][10]

75.60000000000001

In [24]:
players[0]

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [26]:
#Transpose

pt = players.transpose()
pt.shape

(11, 2)

In [27]:
pt = players.transpose()
pt

array([[45.    ,  1.4945],
       [90.    ,  1.5925],
       [72.    ,  1.568 ],
       [81.    ,  1.6905],
       [63.    ,  1.715 ],
       [69.75  ,  1.666 ],
       [74.25  ,  1.568 ],
       [77.4   ,  1.5435],
       [81.    ,  1.519 ],
       [90.    ,  1.617 ],
       [75.6   ,  1.764 ]])

In [29]:
#Statastical and Mathemetical function on players data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))

#Standard deviation
print(np.std(wt_np))

#Corrrlation cofficient
print(np.corrcoef(wt_np,ht_np))

74.45454545454545
75.60000000000001
819.0
12.082941667443528
[[1.         0.16451886]
 [0.16451886 1.        ]]
